# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on: workflow_dispatch #dispatch aguarda que o usuario dispare manualmente

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Printing Greeting...
        run: echo "Hello World!"
      - name: Printing Goodbye...
        run: echo "Done - bye!"
     
